/*
Generated by uvusbreplay 0.1
uvusbreplay copyright 2011 John McMaster <JohnDMcMaster@gmail.com>
Date: 10/22/11 13:14:03.
Source data: /home/mcmaster/document/external/uvscopetek/captures/twain_image/wireshark/1/640x320_wireshark.cap
Source range: 124 - 205
*/
int n_rw = 0;
char buff[64];
//Generated from packet 124/125
n_rw = usb_control_msg(dev->udev, usb_sndctrlpipe(dev->udev, 0), 0x01, USB_DIR_OUT | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x000F, NULL, 0, 500);
if (validate_write(0, n_rw, "packet 124/125") < 0)
	return 1;
//Generated from packet 126/127
n_rw = usb_control_msg(dev->udev, usb_sndctrlpipe(dev->udev, 0), 0x01, USB_DIR_OUT | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x000F, NULL, 0, 500);
if (validate_write(0, n_rw, "packet 126/127") < 0)
	return 1;
//Generated from packet 128/129
n_rw = usb_control_msg(dev->udev, usb_sndctrlpipe(dev->udev, 0), 0x01, USB_DIR_OUT | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x000F, NULL, 0, 500);
if (validate_write(0, n_rw, "packet 128/129") < 0)
	return 1;
//Generated from packet 130/131
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0103, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 130/131") < 0)
	return 1;
//Generated from packet 132/133
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 132/133") < 0)
	return 1;
//Generated from packet 134/135
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0A, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x3000, buff, 3, 500);
if (validate_read((char[]){0x2B, 0x00, 0x08}, 3, buff, n_rw, "packet 134/135") < 0)
	return 1;
//Generated from packet 136/137
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 136/137") < 0)
	return 1;
//Generated from packet 138/139
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0020, 0x0344, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 138/139") < 0)
	return 1;
//Generated from packet 140/141
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0CA1, 0x0348, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 140/141") < 0)
	return 1;
//Generated from packet 142/143
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0020, 0x0346, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 142/143") < 0)
	return 1;
//Generated from packet 144/145
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0981, 0x034A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 144/145") < 0)
	return 1;
//Generated from packet 146/147
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x02FC, 0x3040, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 146/147") < 0)
	return 1;
//Generated from packet 148/149
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0002, 0x0400, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 148/149") < 0)
	return 1;
//Generated from packet 150/151
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0014, 0x0404, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 150/151") < 0)
	return 1;
//Generated from packet 152/153
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0280, 0x034C, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 152/153") < 0)
	return 1;
//Generated from packet 154/155
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x01E0, 0x034E, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 154/155") < 0)
	return 1;
//Generated from packet 156/157
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x02C0, 0x300A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 156/157") < 0)
	return 1;
//Generated from packet 158/159
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0E00, 0x300C, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 158/159") < 0)
	return 1;
//Generated from packet 160/161
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 160/161") < 0)
	return 1;
//Generated from packet 162/163
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0100, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 162/163") < 0)
	return 1;
//Generated from packet 164/165
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 164/165") < 0)
	return 1;
//Generated from packet 166/167
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0004, 0x0300, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 166/167") < 0)
	return 1;
//Generated from packet 168/169
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x0302, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 168/169") < 0)
	return 1;
//Generated from packet 170/171
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0008, 0x0308, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 170/171") < 0)
	return 1;
//Generated from packet 172/173
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x030A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 172/173") < 0)
	return 1;
//Generated from packet 174/175
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0004, 0x0304, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 174/175") < 0)
	return 1;
//Generated from packet 176/177
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0020, 0x0306, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 176/177") < 0)
	return 1;
//Generated from packet 178/179
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x90D8, 0x301A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 178/179") < 0)
	return 1;
//Generated from packet 180/181
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 180/181") < 0)
	return 1;
//Generated from packet 182/183
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0100, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 182/183") < 0)
	return 1;
//Generated from packet 184/185
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0A, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x300C, buff, 3, 500);
if (validate_read((char[]){0x0E, 0x00, 0x08}, 3, buff, n_rw, "packet 184/185") < 0)
	return 1;
//Generated from packet 186/187
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x90D8, 0x301A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 186/187") < 0)
	return 1;
//Generated from packet 188/189
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0805, 0x3064, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 188/189") < 0)
	return 1;
//Generated from packet 190/191
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 190/191") < 0)
	return 1;
//Generated from packet 192/193
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0100, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 192/193") < 0)
	return 1;
//Generated from packet 194/195
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x0402, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 194/195") < 0)
	return 1;
//Generated from packet 196/197
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 196/197") < 0)
	return 1;
//Generated from packet 198/199
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 198/199") < 0)
	return 1;
//Generated from packet 200/201
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x01F4, 0x3012, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 200/201") < 0)
	return 1;
//Generated from packet 202/203
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x023E, 0x305E, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 202/203") < 0)
	return 1;
//Generated from packet 204/205
n_rw = usb_control_msg(dev->udev, usb_sndctrlpipe(dev->udev, 0), 0x01, USB_DIR_OUT | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0003, 0x000F, NULL, 0, 500);
if (validate_write(0, n_rw, "packet 204/205") < 0)
	return 1;

