/*
Generated by uvusbreplay 0.1
uvusbreplay copyright 2011 John McMaster <JohnDMcMaster@gmail.com>
Date: 10/22/11 16:36:24.
Source data: ../captures/twain_image/wireshark/2/640x480_twain.cap
Source range: 73 - 154
*/
int n_rw = 0;
char buff[64];
//Generated from packet 79/80
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0103, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 79/80") < 0)
	return 1;
//Generated from packet 81/82
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 81/82") < 0)
	return 1;
//Generated from packet 83/84
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0A, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x3000, buff, 3, 500);
if (validate_read((char[]){0x2B, 0x00, 0x08}, 3, buff, n_rw, "packet 83/84") < 0)
	return 1;
//Generated from packet 85/86
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 85/86") < 0)
	return 1;
//Generated from packet 87/88
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0020, 0x0344, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 87/88") < 0)
	return 1;
//Generated from packet 89/90
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0CA1, 0x0348, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 89/90") < 0)
	return 1;
//Generated from packet 91/92
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0020, 0x0346, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 91/92") < 0)
	return 1;
//Generated from packet 93/94
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0981, 0x034A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 93/94") < 0)
	return 1;
//Generated from packet 95/96
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x02FC, 0x3040, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 95/96") < 0)
	return 1;
//Generated from packet 97/98
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0002, 0x0400, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 97/98") < 0)
	return 1;
//Generated from packet 99/100
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0014, 0x0404, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 99/100") < 0)
	return 1;
//Generated from packet 101/102
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0280, 0x034C, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 101/102") < 0)
	return 1;
//Generated from packet 103/104
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x01E0, 0x034E, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 103/104") < 0)
	return 1;
//Generated from packet 105/106
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x02C0, 0x300A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 105/106") < 0)
	return 1;
//Generated from packet 107/108
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0E00, 0x300C, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 107/108") < 0)
	return 1;
//Generated from packet 109/110
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 109/110") < 0)
	return 1;
//Generated from packet 111/112
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0100, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 111/112") < 0)
	return 1;
//Generated from packet 113/114
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 113/114") < 0)
	return 1;
//Generated from packet 115/116
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0004, 0x0300, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 115/116") < 0)
	return 1;
//Generated from packet 117/118
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x0302, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 117/118") < 0)
	return 1;
//Generated from packet 119/120
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0008, 0x0308, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 119/120") < 0)
	return 1;
//Generated from packet 121/122
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x030A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 121/122") < 0)
	return 1;
//Generated from packet 123/124
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0004, 0x0304, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 123/124") < 0)
	return 1;
//Generated from packet 125/126
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0020, 0x0306, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 125/126") < 0)
	return 1;
//Generated from packet 127/128
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x90D8, 0x301A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 127/128") < 0)
	return 1;
//Generated from packet 129/130
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 129/130") < 0)
	return 1;
//Generated from packet 131/132
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0100, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 131/132") < 0)
	return 1;
//Generated from packet 133/134
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0A, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x300C, buff, 3, 500);
if (validate_read((char[]){0x0E, 0x00, 0x08}, 3, buff, n_rw, "packet 133/134") < 0)
	return 1;
//Generated from packet 135/136
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x90D8, 0x301A, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 135/136") < 0)
	return 1;
//Generated from packet 137/138
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0805, 0x3064, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 137/138") < 0)
	return 1;
//Generated from packet 139/140
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 139/140") < 0)
	return 1;
//Generated from packet 141/142
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0100, 0x0100, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 141/142") < 0)
	return 1;
//Generated from packet 143/144
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x0402, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 143/144") < 0)
	return 1;
//Generated from packet 145/146
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0001, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 145/146") < 0)
	return 1;
//Generated from packet 147/148
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x0000, 0x0104, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 147/148") < 0)
	return 1;
//Generated from packet 149/150
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x01F4, 0x3012, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 149/150") < 0)
	return 1;
//Generated from packet 151/152
n_rw = usb_control_msg(dev->udev, usb_rcvctrlpipe(dev->udev, 0), 0x0B, USB_DIR_IN | USB_TYPE_VENDOR | USB_RECIP_DEVICE, 0x023E, 0x305E, buff, 1, 500);
if (validate_read((char[]){0x08}, 1, buff, n_rw, "packet 151/152") < 0)
	return 1;

