from uvscada.usb import usb_wraps
from uvscada.bpm import startup
from uvscada.bpm.cmd import bulk2, bulk86
from uvscada.bpm.cmd import sm_read, led_mask_30
from uvscada.bpm.cmd import cmd_20_mk, cmd_49, cmd_02, cmd_50, cmd_50_mk, cmd_0C_mk, cmd_57s, cmd_57_50, cmd_41, cmd_43, cmd_10, cmd_45
from uvscada.bpm.cmd import cmd_4C, cmd_09, cmd_08, cmd_3B, cmd_4A
from uvscada.bpm.cmd import sm_info0, sm_info1, sm_insert, sn_read, sm_info10
from uvscada.bpm.cmd import atomic_probe, gpio_readi, sm_info22, sm_info24, led_mask
from uvscada.util import hexdump, add_bool_arg
from uvscada.usb import validate_read, validate_readv
from uvscada.bpm.cmd import cmd_01
from uvscada.util import hexdump

import read_fw

import usb1
import sys
import inspect
import time

#import uvscada.bpm.pic16f84.read_fw
import uvscada.bpm.pic16f84.write_fw

def replay(dev, cont):
    bulkRead, bulkWrite, controlRead, controlWrite = usb_wraps(dev)
    
    # Generated by uvusbreplay 0.1
    # uvusbreplay copyright 2011 John McMaster <JohnDMcMaster@gmail.com>
    # cmd: /home/mcmaster/bin/usbrply --device 9 -j 11_erase_cont-n.cap
    # Generated from packet 1/2
    # NOTE:: req max 40 but got 18
    buff = controlRead(0x80, 0x06, 0x0100, 0x0000, 40)
    # Req: 40, got: 18
    validate_read(
        "\x12\x01\x00\x02\xFF\xFF\xFF\x40\xB9\x14\x01\x00\x00\x00\x01\x02" \
        "\x00\x01"
        , buff, "packet 1/2")
    # Generated from packet 379/380
    buff = controlWrite(0x02, 0x01, 0x0000, 0x0086, "")
    # Generated from packet 381/382
    buff = controlWrite(0x02, 0x01, 0x0000, 0x0002, "")
    # Generated from packet 383/384
    buff = controlWrite(0x02, 0x01, 0x0000, 0x0088, "")
    # Generated from packet 385/386
    # NOTE:: req max 4096 but got 3
    buff = controlRead(0xC0, 0xB0, 0x0000, 0x0000, 4096)
    # Req: 4096, got: 3
    validate_read("\x00\x00\x00", buff, "packet 385/386")
    # Generated from packet 387/388
    buff = bulk86(dev, target=0x01)
    validate_read("\x16", buff, "packet 387/388")
    # NOTE:: req max 512 but got 4
    # Generated from packet 389/390
    cmd_01(dev)
    # NOTE:: req max 512 but got 136
    # Generated from packet 431/432
    buff = bulk2(dev, 
        "\x43\x19\x08\x00\x00\x3B\x7E\x25\x00\x00\xFE\xFF\x3B\x7C\x25\x00" \
        "\x00\xFE\xFF\x00"
        , target=0x02)
    validate_read("\xA4\x06", buff, "packet W: 431/432, R: 433/434")
    # NOTE:: req max 512 but got 5
    # Generated from packet 435/436
    cmd_01(dev)
    # NOTE:: req max 512 but got 136
    # Generated from packet 439/440
    sn_read(dev)
    # NOTE:: req max 512 but got 35
    # Generated from packet 445/446
    buff = bulk2(dev, 
        "\x14\x38\x25\x00\x00\x04\x00\x90\x32\x90\x00\xA7\x02\x1F\x00\x14" \
        "\x40\x25\x00\x00\x01\x00\x3C\x36\x0E\x01"
        , target=0x20)
    validate_read(
        "\x14\x00\x54\x41\x38\x34\x56\x4C\x56\x5F\x46\x58\x34\x00\x00\x00" \
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x3E\x2C"
        , buff, "packet W: 445/446, R: 447/450")
    # NOTE:: req max 512 but got 35
    # Generated from packet 451/452
    gpio_readi(dev)
    # NOTE:: req max 512 but got 5
    # Generated from packet 455/456
    gpio_readi(dev)
    # NOTE:: req max 512 but got 5
    # Generated from packet 459/460
    sm_info22(dev)
    # NOTE:: req max 512 but got 7
    # Generated from packet 463/464
    sm_info24(dev)
    # NOTE:: req max 512 but got 7
    # Generated from packet 467/468
    sm_read(dev)
    # NOTE:: req max 512 but got 35
    # Generated from packet 473/474
    cmd_01(dev)
    # NOTE:: req max 512 but got 136
    # Generated from packet 477/478
    bulkWrite(0x02, "\x43\x19\x08\x00\x00")
    # Generated from packet 479/480
    bulkWrite(0x02, "\x20\x01\x00\x0C\x04")
    # Generated from packet 481/482
    cmd_41(dev)
    # Generated from packet 483/484
    cmd_10(dev)
    # NOTE:: req max 512 but got 9
    # Generated from packet 487/488
    sm_read(dev)
    # NOTE:: req max 512 but got 35
    # Generated from packet 491/492
    sm_insert(dev)
    # NOTE:: req max 512 but got 35
    # Generated from packet 495/496
    cmd_45(dev)
    # NOTE:: req max 512 but got 103
    # Generated from packet 503/504
    cmd_49(dev)
    # NOTE:: req max 512 but got 5
    # Generated from packet 507/508
    gpio_readi(dev)
    # NOTE:: req max 512 but got 5
    # Generated from packet 511/512
    gpio_readi(dev)
    # NOTE:: req max 512 but got 5
    # Generated from packet 515/516
    sm_info22(dev)
    # NOTE:: req max 512 but got 7
    # Generated from packet 519/520
    sm_info24(dev)
    # NOTE:: req max 512 but got 7
    # Generated from packet 525/526
    sm_read(dev)
    # NOTE:: req max 512 but got 35
    # Generated from packet 531/532
    cmd_49(dev)
    # NOTE:: req max 512 but got 5
    # Generated from packet 535/536
    sm_read(dev)
    # NOTE:: req max 512 but got 35
    # Generated from packet 541/542
    sm_insert(dev)
    # NOTE:: req max 512 but got 35
    # Generated from packet 545/546
    sm_info10(dev)
    # NOTE:: req max 512 but got 11
    # Generated from packet 549/550
    cmd_3B(dev)
    # Generated from packet 551/552
    cmd_4A(dev)
    # NOTE:: req max 512 but got 5
    # Generated from packet 555/556
    cmd_4C(dev)
    # Generated from packet 557/558
    buff = controlWrite(0x40, 0xB2, 0x0000, 0x0000, "")
    # Generated from packet 559/560
    cmd_50(dev, "\x4D\x00")
    # Generated from packet 561/562
    buff = bulk2(dev, 
        "\xE9\x03\x00\x00\x00\x90\x00\x00\xE9\x03\x00\x00\x00\x90\x01\x10" \
        "\xE9\x03\x00\x00\x00\x90\x00\x00\xE9\x03\x00\x00\x00\x90\x01\x80" \
        "\xE9\x02\x00\x00\x00\x90\x00\xE9\x04\x00\x00\x00\x00\x00\x00\x00" \
        "\xE9\x03\x00\x00\x00\x90\x00\x00\xE9\x03\x00\x00\x00\x90\x00\x00" \
        "\x66\xB9\x00\x00\xB2\x00\xFB\xFF\x25\x44\x11\x00\x00"
        , target=0x02)
    validate_read("\x80\x00", buff, "packet W: 561/562, R: 563/564")
    # Generated from packet 565/566
    cmd_02(dev, "\x81\x00\x50\x00\x09\x00")
    # Generated from packet 569/570
    cmd_50(dev, "\xC0\x00")
    # Generated from packet 571/572
    buff = bulk2(dev, 
        "\x66\xB8\x01\x2D\x81\xE3\xFF\xFF\x00\x00\x66\xBB\x18\x00\x66\xC7" \
        "\x05\x30\x40\x00\xC0\xF0\xFF\x89\xD9\xC1\xE1\x02\x66\xC7\x81\x02" \
        "\x00\x00\x00\xF0\xFF\x66\x03\x05\xE4\x46\x00\x00\x66\x89\x05\x90" \
        "\x40\x00\xC0\x89\xDA\x81\xCA\x00\x80\x00\x00\x66\x89\x15\x50\x40" \
        "\x00\xC0\xC6\x05\x14\x22\x00\xC0\x7B\x81\xCA\x00\x40\x00\x00\x66" \
        "\x89\x15\x50\x40\x00\xC0\x89\xD9\x66\xC1\xE1\x02\x66\x89\x81\x00" \
        "\x00\x00\x00\x66\x2B\x05\xE4\x46\x00\x00\xC6\x05\x14\x22\x00\xC0" \
        "\xBB\x81\xCB\x00\x80\x00\x00\x66\x89\x1D\x50\x40\x00\xC0\x89\xC2" \
        "\x81\xE2\x07\x00\x00\x00\x03\xD2\x81\xCA\x01\x00\x00\x00\x89\xD9" \
        "\x81\xE1\x03\x00\x00\x00\xD3\xE2\xD3\xE2\xD3\xE2\xD3\xE2\xD3\xE2" \
        "\xC1\xE2\x0A\x89\xD9\x81\xE1\xFC\x03\x00\x00\x09\xCA\x88\x82\x00" \
        "\x00\x00\x40\x66\xB9\x00\x00\xB2\x00\xFB\xFF\x25\x44\x11\x00\x00"
        , target=0x02)
    validate_read("\x81\x00", buff, "packet W: 571/572, R: 573/574")
    # Generated from packet 575/576
    cmd_02(dev, "\x82\x00\x10\x01\x09\x00")
    # Generated from packet 579/580
    bulkWrite(0x02, "\x08\x01\x09\x04\x57\x81\x00")
    # Generated from packet 581/582
    cmd_02(dev, "\x82\x00\x10\x01\x09\x00")
    # Generated from packet 587/588
    led_mask(dev, "active")
    # Generated from packet 591/592
    cmd_50(dev, "\x18\x00")
    # Generated from packet 593/596
    buff = bulk2(dev, 
        "\x66\xB8\x01\x32\x66\x89\x05\x06\x00\x09\x00\x66\xB9\x00\x00\xB2" \
        "\x00\xFB\xFF\x25\x44\x11\x00\x00"
        , target=0x02)
    validate_read("\x82\x00", buff, "packet W: 593/596, R: 597/598")
    # Generated from packet 599/600
    cmd_02(dev, "\x83\x00\x30\x01\x09\x00")
    # Generated from packet 603/604
    buff = bulk2(dev, 
        "\x57\x82\x00\x20\x01\x00\x2B\x3B\x0C\x22\x00\xC0\x40\x00\x3B\x0E" \
        "\x22\x00\xC0\x00\x00\x3B\x1A\x22\x00\xC0\x18\x00\x0E\x01"
        , target=0x20)
    validate_read(
        "\x14\x00\x54\x41\x38\x34\x56\x4C\x56\x5F\x46\x58\x34\x00\x00\x00" \
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x3E\x2C"
        , buff, "packet W: 603/604, R: 605/616")
    # Generated from packet 617/618
    gpio_readi(dev)
    # Generated from packet 623/624
    gpio_readi(dev)
    # Generated from packet 629/630
    sm_info22(dev)
    # Generated from packet 633/634
    sm_info24(dev)
    # Generated from packet 639/640
    sm_read(dev)
    # Generated from packet 643/644
    buff = bulk2(dev, "\x48\x00\x10\x82\x02", target=0x06)
    validate_read("\x82\x00\x10\x01\x09\x00", buff, "packet W: 643/644, R: 645/646")
    # Generated from packet 649/650
    bulkWrite(0x02, "\x20\x01\x00\x50\x7D\x02\x00\x00")
    # Generated from packet 651/652
    buff = bulk2(dev, uvscada.bpm.pic16f84.write_fw.p651, target=0x02)
    validate_read("\x82\x00", buff, "packet W: 651/652, R: 653/654")
    # Generated from packet 655/656
    cmd_02(dev, "\x83\x00\x90\x03\x09\x00")
    # Generated from packet 659/660
    bulkWrite(0x02, "\x57\x82\x00\x50\x1D\x00\x00\x00")
    # Generated from packet 661/662
    buff = bulk2(dev, 
        "\xC7\x05\x74\x46\x00\x00\x0B\x00\x00\x00\xFF\x15\x38\x11\x00\x00" \
        "\x66\xB9\x00\x00\xB2\x00\xFB\xFF\x25\x44\x11\x00\x00"
        , target=0x02)
    validate_read("\x83\x00", buff, "packet W: 661/662, R: 663/664")
    # Generated from packet 665/666
    cmd_02(dev, "\x84\x00\xB0\x03\x09\x00")
    # Generated from packet 669/670
    bulkWrite(0x02, "\x57\x83\x00\x50\x36\x00\x00\x00")
    # Generated from packet 671/672
    buff = bulk2(dev, 
        "\x00\x00\x3C\x00\x38\x00\x34\x00\x30\x00\x00\x00\x39\x00\x35\x00" \
        "\x31\x00\x3E\x00\x2E\x00\x21\x00\x25\x00\x29\x00\x1C\x00\x20\x00" \
        "\x24\x00\x28\x00\x2C\x00\x00\x00\x04\x00\x08\x00\x0C\x00\x10\x00" \
        "\x14\x00\x18\x00\x1C\x00"
        , target=0x02)
    validate_read("\x84\x00", buff, "packet W: 671/672, R: 673/674")
    # Generated from packet 675/676
    cmd_02(dev, "\x85\x00\xF0\x03\x09\x00")
    # Generated from packet 679/680
    bulkWrite(0x02, 
        "\x1D\xB0\x03\x09\x00\x12\x00\x15\x60\x00\x00\x00\x00\x00\x00\x00" \
        "\x00\x10\x00\x00\x00\x00\x1C\x30\x00\x10\x00\x00\x00\x00\x00\x48" \
        "\x00"
        )
    # Generated from packet 681/682
    cmd_50(dev, "\x17\x00")
    # Generated from packet 683/684
    buff = bulk2(dev, 
        "\xC7\x05\x2C\x00\x09\x00\x10\x00\x00\x00\x66\xB9\x00\x00\xB2\x00" \
        "\xFB\xFF\x25\x44\x11\x00\x00"
        , target=0x02)
    validate_read("\x85\x00", buff, "packet W: 683/684, R: 685/686")
    # Generated from packet 687/688
    cmd_02(dev, "\x86\x00\x10\x04\x09\x00")
    # Generated from packet 879/880
    bulkWrite(0x02, "\x57\x85\x00\x50\x18\x00\x00\x00")
    # Generated from packet 881/882
    buff = bulk2(dev, 
        "\x66\xB8\x01\x32\x66\x89\x05\x06\x00\x09\x00\x66\xB9\x00\x00\xB2" \
        "\x00\xFB\xFF\x25\x44\x11\x00\x00"
        , target=0x02)
    validate_read("\x86\x00", buff, "packet W: 881/882, R: 883/884")
    # Generated from packet 885/886
    cmd_02(dev, "\x87\x00\x30\x04\x09\x00")
    # Generated from packet 889/890
    bulkWrite(0x02, "\x57\x86\x00\x50\xD1\x06\x00\x00")
    # Generated from packet 891/892
    buff = bulk2(dev, uvscada.bpm.pic16f84.write_fw.p891, target=0x02)
    validate_read("\x87\x00", buff, "packet W: 891/892, R: 893/894")
    # Generated from packet 895/896
    cmd_02(dev, "\x88\x00\x10\x0B\x09\x00")
    # Generated from packet 899/900
    cmd_57s(dev, "\x87", "\x00\x00")
    # Generated from packet 903/904
    cmd_50(dev, "\x68\x09")
    # Generated from packet 905/906
    buff = bulk2(dev, uvscada.bpm.pic16f84.write_fw.p905, target=0x02)
    validate_read("\x88\x00", buff, "packet W: 905/906, R: 907/908")
    # Generated from packet 909/910
    cmd_02(dev, "\x89\x00\x80\x14\x09\x00")
    # Generated from packet 913/914
    cmd_57s(dev, "\x88", "\x00\x00")
    # Generated from packet 917/918
    cmd_50(dev, "\xCE\x03")
    # Generated from packet 919/920
    buff = bulk2(dev, uvscada.bpm.pic16f84.write_fw.p919, target=0x02)
    validate_read("\x89\x00", buff, "packet W: 919/920, R: 921/922")
    # Generated from packet 923/924
    cmd_02(dev, "\x8A\x00\x50\x18\x09\x00")
    # Generated from packet 927/928
    cmd_57s(dev, "\x89", "\x00\x00")
    # Generated from packet 931/932
    cmd_50(dev, "\x0D\x00")
    # Generated from packet 933/934
    buff = bulk2(dev, "\x66\xB9\x00\x00\xB2\x00\xFB\xFF\x25\x44\x11\x00\x00", target=0x02)
    validate_read("\x8A\x00", buff, "packet W: 933/934, R: 935/936")
    # Generated from packet 937/938
    cmd_02(dev, "\x8B\x00\x60\x18\x09\x00")
    # Generated from packet 941/942
    bulkWrite(0x02, "\x57\x8A\x00\x50\x1A\x00\x00\x00")
    # Generated from packet 943/944
    buff = bulk2(dev, 
        "\x66\xB9\x00\x00\xB2\x02\xFB\xFF\x25\x44\x11\x00\x00\x66\xB9\x00" \
        "\x00\xB2\x02\xFB\xFF\x25\x44\x11\x00\x00"
        , target=0x02)
    validate_read("\x8B\x00", buff, "packet W: 943/944, R: 945/946")
    # Generated from packet 947/948
    cmd_02(dev, "\x8C\x00\x80\x18\x09\x00")
    # Generated from packet 951/952
    cmd_57s(dev, "\x8B", "\x00\x00")
    # Generated from packet 955/956
    led_mask(dev, "pass")
    # Generated from packet 959/960
    gpio_readi(dev)
    # Generated from packet 963/964
    gpio_readi(dev)
    # Generated from packet 967/968
    sm_info22(dev)
    # Generated from packet 971/972
    sm_info24(dev)
    # Generated from packet 975/976
    sm_read(dev)
    # Generated from packet 979/980
    cmd_49(dev)
    # Generated from packet 983/984
    sm_read(dev)
    # Generated from packet 987/988
    sm_insert(dev)
    # Generated from packet 991/992
    sm_info10(dev)
