# Generated by uvusbreplay 0.1
# uvusbreplay copyright 2011 John McMaster <JohnDMcMaster@gmail.com>
# cmd: /usr/local/bin/usbrply --device 117 2018-03-03_02_start_sw.pcapng
        
import binascii
import time
import usb1

def usb_wraps(dev):
    # Shorten stack traces to simplify errors
    def bulkRead(endpoint, length, timeout=None):
        if timeout is None:
            timeout = 1000
        return dev.bulkRead(endpoint, length, timeout=timeout)

    def bulkWrite(endpoint, data, timeout=None):
        if timeout is None:
            timeout = 1000
        dev.bulkWrite(endpoint, data, timeout=timeout)
    
    def controlRead(request_type, request, value, index, length,
                    timeout=None):
        if timeout is None:
            timeout = 1000
        return dev.controlRead(request_type, request, value, index, length,
                    timeout=timeout)

    def controlWrite(request_type, request, value, index, data,
                     timeout=None):
        if timeout is None:
            timeout = 1000
        dev.controlWrite(request_type, request, value, index, data,
                     timeout=timeout)
    
    return bulkRead, bulkWrite, controlRead, controlWrite

def validate_read(expected, actual, msg):
    if expected != actual:
        print 'Failed %s' % msg
        print '  Expected; %s' % binascii.hexlify(expected,)
        print '  Actual:   %s' % binascii.hexlify(actual,)
        #raise Exception('failed validate: %s' % msg)

def start_sw(dev):
    bulkRead, bulkWrite, controlRead, controlWrite = usb_wraps(dev)

    # Generated from packet 31/32
    buff = controlRead(0xC0, 0x5F, 0x0000, 0x0000, 8)
    # NOTE:: req max 8 but got 2
    validate_read("\x30\x00", buff, "packet 31/32")
    # Generated from packet 83/85
    bulkWrite(0x02, "\xA0")
    # Generated from packet 84/86
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 84/86")
    # Generated from packet 87/88
    controlWrite(0x40, 0xB1, 0x0102, 0x0000, "")
    # Generated from packet 1249/1251
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1250/1252
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1250/1252")
    # Generated from packet 1253/1254
    bulkWrite(0x02, "\xA6\x00\x41\x4B\x30\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46"
                "\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46"
                "\xA6\xA4")
    # Generated from packet 1255/1257
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1256/1258
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1256/1258")
    # Generated from packet 1259/1261
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1260/1262
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1260/1262")
    # Generated from packet 1263/1265
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1264/1266
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1264/1266")
    # Generated from packet 1267/1269
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1268/1270
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1268/1270")
    # Generated from packet 1271/1273
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1272/1274
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1272/1274")
    # Generated from packet 1275/1277
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1276/1278
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1276/1278")
    # Generated from packet 1279/1281
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1280/1282
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1280/1282")
    # Generated from packet 1283/1285
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1284/1286
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1284/1286")
    # Generated from packet 1287/1289
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1288/1290
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1288/1290")
    # Generated from packet 1291/1293
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1292/1294
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1292/1294")
    # Generated from packet 1295/1297
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1296/1298
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1296/1298")
    # Generated from packet 1299/1301
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1300/1302
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1300/1302")
    # Generated from packet 1303/1305
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1304/1306
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1304/1306")
    # Generated from packet 1307/1309
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1308/1310
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1308/1310")
    # Generated from packet 1311/1313
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1312/1314
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1312/1314")
    # Generated from packet 1315/1317
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1316/1318
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1316/1318")
    # Generated from packet 1319/1321
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1320/1322
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1320/1322")
    # Generated from packet 1323/1325
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1324/1326
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1324/1326")
    # Generated from packet 1327/1329
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1328/1330
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1328/1330")
    # Generated from packet 1331/1333
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1332/1334
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1332/1334")
    # Generated from packet 1335/1337
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1336/1338
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1336/1338")
    # Generated from packet 1339/1341
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1340/1342
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1340/1342")
    # Generated from packet 1343/1345
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1344/1346
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1344/1346")
    # Generated from packet 1347/1349
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1348/1350
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1348/1350")
    # Generated from packet 1351/1353
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1352/1354
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1352/1354")
    # Generated from packet 1355/1357
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1356/1358
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1356/1358")
    # Generated from packet 1359/1361
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1360/1362
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1360/1362")
    # Generated from packet 1363/1365
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1364/1366
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1364/1366")
    # Generated from packet 1367/1369
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1368/1370
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1368/1370")
    # Generated from packet 1371/1373
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1372/1374
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1372/1374")
    # Generated from packet 1375/1377
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1376/1378
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1376/1378")
    # Generated from packet 1379/1381
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1380/1382
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1380/1382")
    # Generated from packet 1383/1385
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1384/1386
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1384/1386")
    # Generated from packet 1387/1389
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1388/1390
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1388/1390")
    # Generated from packet 1391/1393
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1392/1394
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1392/1394")
    # Generated from packet 1395/1397
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1396/1398
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1396/1398")
    # Generated from packet 1399/1401
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1400/1402
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1400/1402")
    # Generated from packet 1403/1405
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1404/1406
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1404/1406")
    # Generated from packet 1407/1409
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1408/1410
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1408/1410")
    # Generated from packet 1411/1413
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1412/1414
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1412/1414")
    # Generated from packet 1415/1416
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1417/1418
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1417/1418")
    # Generated from packet 1419/1421
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1420/1422
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1420/1422")
    # Generated from packet 1423/1425
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1424/1426
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1424/1426")
    # Generated from packet 1427/1429
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1428/1430
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1428/1430")
    # Generated from packet 1431/1432
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1433/1434
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1433/1434")
    # Generated from packet 1435/1436
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1437/1438
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1437/1438")
    # Generated from packet 1439/1441
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1440/1442
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1440/1442")
    # Generated from packet 1443/1445
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1444/1446
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1444/1446")
    # Generated from packet 1447/1448
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1449/1450
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1449/1450")
    # Generated from packet 1451/1453
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1452/1454
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1452/1454")
    # Generated from packet 1455/1457
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1456/1458
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1456/1458")
    # Generated from packet 1459/1461
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1460/1462
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1460/1462")
    # Generated from packet 1463/1465
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1464/1466
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1464/1466")
    # Generated from packet 1467/1469
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1468/1470
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1468/1470")
    # Generated from packet 1471/1473
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1472/1474
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1472/1474")
    # Generated from packet 1475/1477
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1476/1478
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1476/1478")
    # Generated from packet 1479/1481
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1480/1482
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1480/1482")
    # Generated from packet 1483/1485
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1484/1486
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1484/1486")
    # Generated from packet 1487/1489
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1488/1490
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1488/1490")
    # Generated from packet 1491/1493
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1492/1494
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1492/1494")
    # Generated from packet 1495/1497
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1496/1498
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1496/1498")
    # Generated from packet 1499/1501
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1500/1502
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1500/1502")
    # Generated from packet 1503/1505
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1504/1506
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1504/1506")
    # Generated from packet 1507/1509
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1508/1510
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1508/1510")
    # Generated from packet 1511/1513
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1512/1514
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1512/1514")
    # Generated from packet 1515/1517
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1516/1518
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1516/1518")
    # Generated from packet 1519/1521
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1520/1522
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1520/1522")
    # Generated from packet 1523/1525
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1524/1526
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1524/1526")
    # Generated from packet 1527/1529
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1528/1530
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1528/1530")
    # Generated from packet 1531/1533
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1532/1534
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x4F\x08\x13\x00", buff, "packet 1532/1534")
    # Generated from packet 1535/1537
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1536/1538
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1536/1538")
    # Generated from packet 1539/1541
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1540/1542
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1540/1542")
    # Generated from packet 1543/1545
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1544/1546
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1544/1546")
    # Generated from packet 1547/1549
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1548/1550
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1548/1550")
    # Generated from packet 1551/1553
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1552/1554
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1552/1554")
    # Generated from packet 1555/1557
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1556/1558
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1556/1558")
    # Generated from packet 1559/1560
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1561/1562
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1561/1562")
    # Generated from packet 1563/1564
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1565/1566
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1565/1566")
    # Generated from packet 1567/1569
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1568/1570
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1568/1570")
    # Generated from packet 1571/1573
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1572/1574
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1572/1574")
    # Generated from packet 1575/1577
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1576/1578
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 1576/1578")
    # Generated from packet 1579/1581
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1580/1582
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1580/1582")
    # Generated from packet 1583/1585
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1584/1586
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 1584/1586")
    # Generated from packet 1587/1588
    bulkWrite(0x02, "\xA6\x00\x41\xA2\xE8\xB2\xDD\x32\x3D\x41\x53\x30\xE8\x3D\xA0\x6E"
                "\xB5\x4A\x58\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46"
                "\xA6\x34")
    # Generated from packet 1589/1591
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1590/1592
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCC\x5F\x08\x13\x00", buff, "packet 1590/1592")
    # Generated from packet 1593/1595
    bulkWrite(0x02, "\xA0")
    # Generated from packet 1594/1596
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCC\x6F\x08\x13\x00", buff, "packet 1594/1596")

def init_dev(dev):
    bulkRead, bulkWrite, controlRead, controlWrite = usb_wraps(dev)

    # Generated from packet 31/32
    bulkWrite(0x02, "\xA6\x00\x49\x50\x50\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46"
                "\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46"
                "\xA6\xE4")
    # Generated from packet 33/35
    bulkWrite(0x02, "\xA0")
    # Generated from packet 34/36
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 34/36")
    # Generated from packet 37/39
    bulkWrite(0x02, "\xA0")
    # Generated from packet 38/40
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x5F\x08\x13\x00", buff, "packet 38/40")
    # Generated from packet 41/43
    bulkWrite(0x02, "\xA0")
    # Generated from packet 42/44
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 42/44")
    # Generated from packet 45/47
    bulkWrite(0x02, "\xA0")
    # Generated from packet 46/48
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x4F\x08\x13\x00", buff, "packet 46/48")
    # Generated from packet 49/51
    bulkWrite(0x02, "\xA0")
    # Generated from packet 50/52
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 50/52")
    # Generated from packet 53/54
    bulkWrite(0x02, "\xA0")
    # Generated from packet 55/56
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 55/56")
    # Generated from packet 57/59
    bulkWrite(0x02, "\xA0")
    # Generated from packet 58/60
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x5F\x08\x13\x00", buff, "packet 58/60")
    # Generated from packet 61/63
    bulkWrite(0x02, "\xA0")
    # Generated from packet 62/64
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 62/64")
    # Generated from packet 65/67
    bulkWrite(0x02, "\xA0")
    # Generated from packet 66/68
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 66/68")
    # Generated from packet 69/71
    bulkWrite(0x02, "\xA0")
    # Generated from packet 70/72
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 70/72")
    # Generated from packet 73/75
    bulkWrite(0x02, "\xA0")
    # Generated from packet 74/76
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 74/76")
    # Generated from packet 77/79
    bulkWrite(0x02, "\xA0")
    # Generated from packet 78/80
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 78/80")
    # Generated from packet 81/83
    bulkWrite(0x02, "\xA0")
    # Generated from packet 82/84
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 82/84")
    # Generated from packet 85/87
    bulkWrite(0x02, "\xA0")
    # Generated from packet 86/88
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 86/88")
    # Generated from packet 89/90
    bulkWrite(0x02, "\xA0")
    # Generated from packet 91/92
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 91/92")
    # Generated from packet 93/95
    bulkWrite(0x02, "\xA0")
    # Generated from packet 94/96
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 94/96")
    # Generated from packet 97/99
    bulkWrite(0x02, "\xA0")
    # Generated from packet 98/100
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 98/100")
    # Generated from packet 101/102
    bulkWrite(0x02, "\xA0")
    # Generated from packet 103/104
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 103/104")
    # Generated from packet 105/107
    bulkWrite(0x02, "\xA0")
    # Generated from packet 106/108
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 106/108")
    # Generated from packet 109/111
    bulkWrite(0x02, "\xA0")
    # Generated from packet 110/112
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 110/112")
    # Generated from packet 113/114
    bulkWrite(0x02, "\xA0")
    # Generated from packet 115/116
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 115/116")
    # Generated from packet 117/119
    bulkWrite(0x02, "\xA0")
    # Generated from packet 118/120
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 118/120")
    # Generated from packet 121/122
    bulkWrite(0x02, "\xA0")
    # Generated from packet 123/124
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 123/124")
    # Generated from packet 125/127
    bulkWrite(0x02, "\xA0")
    # Generated from packet 126/128
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 126/128")
    # Generated from packet 129/130
    bulkWrite(0x02, "\xA0")
    # Generated from packet 131/132
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 131/132")
    # Generated from packet 133/135
    bulkWrite(0x02, "\xA0")
    # Generated from packet 134/136
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 134/136")
    # Generated from packet 137/139
    bulkWrite(0x02, "\xA0")
    # Generated from packet 138/140
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 138/140")
    # Generated from packet 141/143
    bulkWrite(0x02, "\xA0")
    # Generated from packet 142/144
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 142/144")
    # Generated from packet 145/147
    bulkWrite(0x02, "\xA0")
    # Generated from packet 146/148
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x4F\x08\x13\x00", buff, "packet 146/148")
    # Generated from packet 149/151
    bulkWrite(0x02, "\xA0")
    # Generated from packet 150/152
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x5F\x08\x13\x00", buff, "packet 150/152")
    # Generated from packet 153/155
    bulkWrite(0x02, "\xA0")
    # Generated from packet 154/156
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x5F\x08\x13\x00", buff, "packet 154/156")
    # Generated from packet 157/159
    bulkWrite(0x02, "\xA0")
    # Generated from packet 158/160
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x4F\x08\x13\x00", buff, "packet 158/160")
    # Generated from packet 161/163
    bulkWrite(0x02, "\xA0")
    # Generated from packet 162/164
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 162/164")
    # Generated from packet 165/167
    bulkWrite(0x02, "\xA0")
    # Generated from packet 166/168
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 166/168")
    # Generated from packet 169/170
    bulkWrite(0x02, "\xA0")
    # Generated from packet 171/172
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 171/172")
    # Generated from packet 173/174
    bulkWrite(0x02, "\xA0")
    # Generated from packet 175/176
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 175/176")
    # Generated from packet 177/179
    bulkWrite(0x02, "\xA0")
    # Generated from packet 178/180
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x6F\x08\x13\x00", buff, "packet 178/180")
    # Generated from packet 181/183
    bulkWrite(0x02, "\xA0")
    # Generated from packet 182/184
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xEE\x5F\x08\x13\x00", buff, "packet 182/184")
    # Generated from packet 185/187
    bulkWrite(0x02, "\xA0")
    # Generated from packet 186/188
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x5F\x08\x13\x00", buff, "packet 186/188")
    # Generated from packet 189/190
    bulkWrite(0x02, "\xA6\x00\x52\x7C\x6E\x42\x7A\x31\x33\x36\x53\x31\x50\x46\x46\x46"
                "\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46"
                "\xA6\x70")
    # Generated from packet 191/193
    bulkWrite(0x02, "\xA0")
    # Generated from packet 192/194
    buff = bulkRead(0x82, 0x0020)
    # NOTE:: req max 32 but got 6
    validate_read("\xFF\xCE\x6F\x08\x13\x00", buff, "packet 192/194")

def open_dev(usbcontext=None):
    if usbcontext is None:
        usbcontext = usb1.USBContext()
    
    print 'Scanning for devices...'
    for udev in usbcontext.getDeviceList(skip_on_error=True):
        vid = udev.getVendorID()
        pid = udev.getProductID()
        if (vid, pid) == (0x14b9, 0x0001):
            print
            print
            print 'Found device'
            print 'Bus %03i Device %03i: ID %04x:%04x' % (
                udev.getBusNumber(),
                udev.getDeviceAddress(),
                vid,
                pid)
            return udev.open()
    raise Exception("Failed to find a device")

if __name__ == "__main__":
    import argparse 
    
    parser = argparse.ArgumentParser(description='Replay captured USB packets')
    args = parser.parse_args()

    usbcontext = usb1.USBContext()
    dev = open_dev(usbcontext)
    dev.claimInterface(0)
    dev.resetDevice()

    start_sw(dev)
    init_dev(dev)


